# Generated by Django 4.2 on 2023-09-24 19:14

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model

def create_auth_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Collaborators')
    Group.objects.get_or_create(name='Authors')
    user = get_user_model().objects.create_user(username='testuser', password='testpass')
    user.groups.add(Group.objects.get(name='Authors'))


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_auth_groups),
    ]

